{{- if and (eq .Values.storage "sqlite") .Values.sqlite.persistence.enabled (not .Values.sqlite.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "proxyharbor.fullname" . }}-data
  labels:
    {{- include "proxyharbor.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sqlite.persistence.size | quote }}
  {{- if .Values.sqlite.persistence.storageClass }}
  storageClassName: {{ .Values.sqlite.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
